//! §3's core mechanism: deciding, per packet, whether it's in the sampled
//! set that gets forwarded in full to the recomputation server — using a
//! verifier-supplied key, never one the gateway (and therefore the prover,
//! who hosts the gateway) generates itself.
//!
//! Reuses §2's SipHash-1-3-128: it's already the fastest of the three
//! frame-hash candidates benchmarked there, and a per-packet sampling
//! decision has to run at the same line rate as everything else in the
//! pipeline — there's no budget for a second, slower primitive just for
//! this.

use crate::hashing::siphash13_128;

/// Turn a probability (recomputation budget C, from §1) into a threshold
/// on a uniform 64-bit hash output. P(hash_output < threshold) == c.
pub fn threshold_for_rate(c: f64) -> u64 {
    debug_assert!((0.0..=1.0).contains(&c));
    (c * u64::MAX as f64) as u64
}

/// The sampling decision itself. `key` is verifier-supplied and never
/// generated by the gateway. `packet_id` must be a canonical, fixed
/// function of immutable packet fields (this document uses 5-tuple +
/// TCP sequence number) — the gateway has no discretion over *how*
/// packet_id is computed, only evaluates the PRF against it. That's the
/// dumb/smart split for this specific decision: identifying the packet is
/// mechanical, deciding whether it's sampled is the only place the
/// verifier's secret enters.
#[inline]
pub fn sample_decision(key: &[u8; 16], packet_id: u64, threshold: u64) -> bool {
    let h = siphash13_128(key, &packet_id.to_le_bytes());
    let v = u64::from_le_bytes(h[0..8].try_into().unwrap());
    v < threshold
}

/// Canonical packet identifier: 5-tuple + TCP sequence number, fixed
/// encoding, no gateway discretion.
pub fn packet_id(src_ip: [u8; 4], dst_ip: [u8; 4], src_port: u16, dst_port: u16, seq: u32) -> u64 {
    let mut buf = [0u8; 16];
    buf[0..4].copy_from_slice(&src_ip);
    buf[4..8].copy_from_slice(&dst_ip);
    buf[8..10].copy_from_slice(&src_port.to_le_bytes());
    buf[10..12].copy_from_slice(&dst_port.to_le_bytes());
    buf[12..16].copy_from_slice(&seq.to_le_bytes());
    // Fold with a fixed, public (non-secret) hash — this is an identifier,
    // not a security boundary, so no key here. Reusing siphash13_128 with
    // an arbitrary fixed public key is just a convenient 128->64 bit fold.
    let h = siphash13_128(&[0u8; 16], &buf);
    u64::from_le_bytes(h[0..8].try_into().unwrap())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rate_is_approximately_correct_over_many_packets() {
        let key = [7u8; 16];
        let threshold = threshold_for_rate(0.01);
        let n = 2_000_000u64;
        let sampled = (0..n).filter(|&i| sample_decision(&key, i, threshold)).count();
        let rate = sampled as f64 / n as f64;
        assert!((rate - 0.01).abs() < 0.001, "empirical rate {rate} far from target 0.01");
    }

    #[test]
    fn different_keys_give_uncorrelated_decisions() {
        let k1 = [1u8; 16];
        let k2 = [2u8; 16];
        let threshold = threshold_for_rate(0.5);
        let n = 100_000u64;
        let agree = (0..n)
            .filter(|&i| sample_decision(&k1, i, threshold) == sample_decision(&k2, i, threshold))
            .count();
        let rate = agree as f64 / n as f64;
        // Two independent fair coins agree ~50% of the time. If they
        // agreed much more than that, the "verifier-only key" property
        // would be worthless in practice.
        assert!((rate - 0.5).abs() < 0.02, "agreement rate {rate} suggests key-independence failure");
    }
}
